const defaultCriteria = [
  { key: "endToEnd", label: "End-to-End Recruitment", category: "Recruitment Competencies", keywords: ["end-to-end", "end to end", "full lifecycle", "full cycle", "full-cycle", "sourcing to onboarding", "screening till onboarding"] },
  { key: "talentAcquisition", label: "Talent Acquisition", category: "Recruitment Competencies", keywords: ["talent acquisition", "ta specialist", "recruiter", "recruitment specialist", "talent recruiter", "headhunting", "headhunter"] },
  { key: "bulkHiring", label: "Bulk Hiring", category: "Recruitment Competencies", keywords: ["bulk hiring", "mass hiring", "high volume", "high-volume", "volume recruitment", "large scale", "large-scale"] },
  { key: "whiteCollar", label: "White Collar", category: "Workforce Segments", keywords: ["white collar", "white-collar", "corporate hiring", "executive recruitment", "head office", "c-suite", "administrative role"] },
  { key: "blueCollar", label: "Blue Collar", category: "Workforce Segments", keywords: ["blue collar", "blue-collar", "general worker", "labor", "labour", "technician", "driver", "operator", "bulk worker"] },
  { key: "ats", label: "ATS Systems", category: "Recruitment Tools", keywords: ["ats", "applicant tracking", "ceipal", "ramco", "oracle hcm", "avature", "eightfold", "workday", "greenhouse", "zoho recruit", "taleo", "smartrecruiters", "odoo"] },
  { key: "linkedinRecruiter", label: "LinkedIn Recruiter", category: "Recruitment Tools", keywords: ["linkedin recruiter", "linkedin sourcing", "boolean search", "recruiter seat", "linkedin portal"] },
  { key: "construction", label: "Construction", category: "Industry Specializations", keywords: ["construction", "real estate", "developer", "realty", "property", "cut & bend", "ready-mix", "infrastructure"] },
  { key: "interiorFitOut", label: "Interior Fit-Out", category: "Industry Specializations", keywords: ["interior fit-out", "fit out", "fit-out", "interior design"] },
  { key: "joinery", label: "Joinery", category: "Industry Specializations", keywords: ["joiner", "joinery", "carpenter", "carpentry", "woodwork"] },
  { key: "mep", label: "MEP", category: "Industry Specializations", keywords: ["mep", "mechanical electrical", "hvac", "facility management", "plumbing", "electrical engineer"] },
  { key: "uaeExperience", label: "UAE Experience", category: "Geography", keywords: ["uae", "dubai", "abu dhabi", "sharjah", "mohre", "gdrfa", "nafis", "emiratization", "gulf"] }
];

const candidatesData = [
  {
    id: "c1",
    name: "Kenith Brian D'Almeida",
    title: "HR Recruiter / Talent Acquisition Specialist",
    email: "kenithbrian30@gmail.com",
    phone: "+971-504572548",
    location: "Dubai, JLT, UAE",
    experience: 6,
    education: "MBA in HR & Marketing (2021), Bachelor's in Business Management (2016)",
    languages: ["English", "Hindi", "Konkani", "Malayalam", "Kannada", "Tulu", "Tamil"],
    summary: "Dynamic recruitment professional with 6 years of experience in Mass Hiring, Bulk Hiring campaigns, and Emiratization in the UAE. Highly skilled in stakeholder management and sourcing.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: true,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: true,
      interiorFitOut: false,
      joinery: true,
      mep: true,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Explicitly managed 'End to End Recruitment' at Sundus and Danube Group (screening till onboarding).",
      talentAcquisition: "Worked as a Talent Acquisition Specialist at Sundus and Danube Group.",
      whiteCollar: "Recruited White Collar staff for Danube Properties.",
      blueCollar: "Sourced blue-collar workers through Amnesty centers and direct outreach.",
      bulkHiring: "Successfully managed Mass Hiring campaigns, closing up to 200 hires per month for Danube.",
      ats: "Proficient in ATS platforms including Ceipal, RAMCO, and Oracle HCM.",
      linkedinRecruiter: "Utilized LinkedIn Recruiter and social media for sourcing candidates.",
      construction: "Handled recruitment for Danube Properties and projects like Ready-Mix Concrete (RMC) & Cut & Bend Factory.",
      joinery: "Successfully closed bulk hiring campaigns for 'Joiner' roles in the Danube Cut & Bend factory project.",
      mep: "Managed MEP Facility Management recruitment for Danube Properties (averaging 200/month).",
      uaeExperience: "Based in Dubai, UAE since 2023, working for local firms like Danube Group and Sundus."
    }
  },
  {
    id: "c2",
    name: "Namrata Bawkar",
    title: "HR Specialist / Talent Acquisition",
    email: "namratabawkar1414@gmail.com",
    phone: "+971505944136",
    location: "Bur Dubai, UAE",
    experience: 7,
    education: "MBA in Human Resources (2020), BBA in HR (2016)",
    languages: ["English", "Hindi", "Gujarati", "Marathi", "Arabic (Beginner)"],
    summary: "Results-driven HR & TA professional with 7+ years of experience (4+ in UAE) across Retail, Hospitality, Real Estate, and Construction. Strong stakeholder management and scaling capabilities.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: true,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: true,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Proven expertise in full-cycle end-to-end recruitment from sourcing to onboarding.",
      talentAcquisition: "Held positions as Talent Acquisition Specialist and HR Specialist.",
      whiteCollar: "Recruited front-line to C-suite roles for major holding groups (Landmark, GMG).",
      blueCollar: "Implemented HR trainings specifically tailored for blue collar staff.",
      bulkHiring: "Led high-volume bulk hiring (1000+ hires) across UAE, UK, and Turkey for Reef (Ikcon Restaurant).",
      ats: "Expertise in ATS management: Avature, Eightfold (AI Sourcing), Oracle HRMS, SAP, Workday, and Taleo.",
      linkedinRecruiter: "Certified LinkedIn Recruiter since 2019.",
      construction: "Worked in HR and recruitment within Real Estate and Construction sectors.",
      uaeExperience: "4+ years of professional HR experience in Dubai, UAE (GMG, Deyaar, Landmark, Reef)."
    }
  },
  {
    id: "c3",
    name: "Rupal Tank",
    title: "HR & Operations Manager",
    email: "rupalt@gmail.com",
    phone: "+971554829919",
    location: "Dubai Production City, UAE",
    experience: 14,
    education: "Bachelor of Commerce (Mumbai University), Diploma in HR Management",
    languages: ["English", "Hindi"],
    summary: "Senior HR Leader with over 14 years of experience (10+ in UAE) specializing in diversity, business scaling, and talent growth within Real Estate, Yacht Operations, and Retail sectors.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: true,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: true,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Managed end-to-end recruitment solutions including screening, interviews, offer letters, and onboarding.",
      talentAcquisition: "Spearheaded Talent Acquisition and recruitment strategies for high-profile developers.",
      whiteCollar: "Hired key management, department heads, and B & C level professionals.",
      blueCollar: "Implemented HR trainings and managed general workers/blue collar staff.",
      bulkHiring: "Led bulk hiring campaigns (1000+ hires) for hospitality and major events (Expo 2020 Israel Pavilion).",
      ats: "Worked with HRMS ERP, Horizon ERP, Zoho CRM, and Matrix software.",
      linkedinRecruiter: "Sourced and mapped senior-level talent via LinkedIn.",
      construction: "HR Manager for Hilite Realty LLC & The Luxe Developers (Real Estate Developers, highly adjacent to Construction).",
      uaeExperience: "Over 10 years of experience in Dubai, UAE (Luxe Developers, Expo 2020, Hilite Realty)."
    }
  },
  {
    id: "c4",
    name: "Abdelrahman Magdy Nasr Eldin",
    title: "Human Resources Recruitment Specialist",
    email: "abdelrahmanmagdy122@gmail.com",
    phone: "+971522751228",
    location: "Abu Dhabi, UAE",
    experience: 4,
    education: "Bachelor's Degree in Business Management (2021)",
    languages: ["Arabic (Native)", "English (Fluent)", "French (Proficient)"],
    summary: "Recruitment Specialist with 4 years of experience in BPO and Banking sectors. Expertise in high-volume sourcing, ATS utilization, and Emiratization programs in the UAE.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: true,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Managed comprehensive recruitment cycles from sourcing to onboarding (FAB and Intelcia).",
      talentAcquisition: "Title: Talent Acquisition Specialist at First Abu Dhabi Bank (FAB).",
      whiteCollar: "Tailored recruitment approaches for white-collar positions across corporate functions.",
      blueCollar: "Tailored recruitment approaches for blue-collar positions.",
      bulkHiring: "High-volume recruitment specialist, onboarding 8-10 hires weekly.",
      ats: "Advanced use of Smart Recruiters, Salesforce CRM, Oracle Taleo, and SAP.",
      linkedinRecruiter: "Maximized recruiter productivity through advanced use of LinkedIn Recruiter.",
      uaeExperience: "Currently working at First Abu Dhabi Bank in Abu Dhabi, UAE. Highly active in Emiratization (Nafis program)."
    }
  },
  {
    id: "c5",
    name: "Faiza Ashfaq",
    title: "HR & Talent Acquisition Professional",
    email: "faizaashfaq1990@gmail.com",
    phone: "+971559146120",
    location: "Dubai, UAE",
    experience: 12,
    education: "Master's in Diplomacy & Strategic Studies, CHRP (Certified HR Professional)",
    languages: ["English", "Urdu", "Hindi", "Punjabi"],
    summary: "HR & TA Professional with 12+ years of experience across Telecom, ICT, Construction, Engineering, and Real Estate sectors. Deep knowledge of UAE Labour Law and HR best practices.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: false,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: true,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Coordinated the complete recruitment lifecycle from sourcing to onboarding at XAD Technologies.",
      talentAcquisition: "12+ years of dedicated experience in Talent Acquisition and HR operations.",
      whiteCollar: "Managed recruitment for IT, Telecom, Engineering, and Corporate white-collar roles.",
      bulkHiring: "Successfully managed multiple high-volume recruitment campaigns for corporate projects.",
      ats: "Experienced in using ATS Platforms, ERP Next, and HRIS/ERP systems.",
      linkedinRecruiter: "Sourced and screened candidates extensively through LinkedIn Recruiter.",
      construction: "Recruited directly for the Construction and Engineering sectors at XAD Technologies.",
      uaeExperience: "Based in Dubai/Sharjah, UAE since 2023. Thoroughly versed in UAE Labour Law."
    }
  },
  {
    id: "c6",
    name: "Sanjana Chompfel",
    title: "Senior Talent Acquisition / HR Operations",
    email: "sanjanachompfel34@gmail.com",
    phone: "+971566028682",
    location: "Mankhool, Dubai, UAE",
    experience: 8,
    education: "MBA (2017), Bachelor of Accounting & Finance (2015)",
    languages: ["English", "Hindi", "Marathi"],
    summary: "Senior HR & TA professional with over 8 years of experience across UAE and India. Specialized in end-to-end recruitment, Odoo HRMS, and employee relations.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: true,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Managed full lifecycle recruitment processes from sourcing, screening to onboarding.",
      talentAcquisition: "Senior Talent Acquisition Specialist with a focus on sourcing and pipeline building.",
      whiteCollar: "Hired executive, corporate, and administrative roles.",
      blueCollar: "Managed full-cycle recruitment for blue-collar workforces at Ghassan Aboud Group.",
      bulkHiring: "Assisted with campus recruitment, graduate hiring, and high-volume project sourcing.",
      ats: "Proficient in HRMS / ATS platforms and managed Odoo database updates.",
      linkedinRecruiter: "Skilled in LinkedIn, Indeed, and Naukri Gulf for talent mapping.",
      uaeExperience: "Over 4 years of UAE experience working with Consultant HSS and Al Fakher Tobacco Factory."
    }
  },
  {
    id: "c7",
    name: "Aparna Dewmini",
    title: "Group HR Business Partner",
    email: "aparnadew7@gmail.com",
    phone: "+971589800226",
    location: "Al Nadha, Dubai, UAE",
    experience: 5,
    education: "MSc in Business Psychology (2026), BA in International Business Management (2023)",
    languages: ["English", "Hindi"],
    summary: "HR and Administration professional with over 5 years of experience across HR operations and talent acquisition. Promoted rapidly to lead holding group HR operations in Dubai.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: true,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: false,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Handled full-cycle recruitment across multiple divisions from sourcing to onboarding.",
      talentAcquisition: "5+ years of experience across HR operations and talent acquisition.",
      whiteCollar: "Recruited for white-collar positions and led white-collar L&D programs.",
      blueCollar: "Managed end-to-end blue-collar recruitment to support manufacturing operations (MAS Holdings).",
      bulkHiring: "Managed high-volume blue-collar staffing for manufacturing plants.",
      ats: "Used Oracle and Darwinbox HR Management Systems for tracking and database management.",
      uaeExperience: "Group HR BP for AFM Holding Limited and HR Coordinator for Ghassan Aboud Group in the UAE."
    }
  },
  {
    id: "c8",
    name: "Shalu Sharma",
    title: "Manager - Talent Acquisition / HR BP",
    email: "sharma183shalu@gmail.com",
    phone: "+971543659006",
    location: "Dubai, UAE",
    experience: 11,
    education: "MBA in Human Resources (2015), B.Com (2012)",
    languages: ["English", "Hindi"],
    summary: "HR Manager with 11 years of experience in corporate banking, consumer goods, IT, and healthcare. Specializes in strategic capacity planning and high-volume recruitment.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: false,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Manages the complete recruitment lifecycle from core requirements to final onboarding.",
      talentAcquisition: "Currently Manager - Talent Acquisition at Emirates NBD Bank.",
      whiteCollar: "Sourced for corporate architecture, banking, and leadership positions.",
      bulkHiring: "Delivered over 100 quality hires monthly and managed massive recruitment projects (2000+ professionals).",
      ats: "Consistently utilizes advanced applicant tracking systems to monitor pipelines.",
      linkedinRecruiter: "Listed LinkedIn Recruiter under Technical Skills and actively uses it for sourcing.",
      uaeExperience: "Recruitment Manager at Emirates NBD Bank in Dubai, UAE. Well-versed in UAE labor laws."
    }
  },
  {
    id: "c9",
    name: "Shrinidhi Kumar",
    title: "Senior Talent Acquisition Specialist",
    email: "shrinidhik002@gmail.com",
    phone: "+971567315646",
    location: "Dubai, UAE",
    experience: 9,
    education: "MBA (2023), Bachelor of Commerce (2017)",
    languages: ["English", "Hindi", "Kannada", "French (A2/B1)"],
    summary: "Talent Acquisition Specialist with 9 years of experience in end-to-end recruitment across UAE and global markets for Tech and Non-Tech roles. Track record in high-volume hiring.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: false,
      bulkHiring: true,
      ats: true,
      linkedinRecruiter: true,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "9 years of experience in end-to-end recruitment lifecycle (Accenture, IBM, Dover, Pathway).",
      talentAcquisition: "Senior Talent Acquisition Specialist and Lead at Pathway Ltd, Dubai.",
      whiteCollar: "Sourced for global corporate, tech, and non-tech white-collar roles.",
      bulkHiring: "Co-led large-scale acquisition project (1200+ employees) and onboarded 500+ hires weekly.",
      ats: "Expertise in Workday, Greenhouse, SAP SuccessFactors, Oracle HCM, and Zoho Recruit.",
      linkedinRecruiter: "Extensive use of LinkedIn Recruiter and Boolean search for sourcing.",
      uaeExperience: "Sourced for UAE/GCC markets and currently holds TA Lead role in Dubai, UAE."
    }
  },
  {
    id: "c10",
    name: "Amal Ashok P M",
    title: "HR Manager",
    email: "amalashokpma@gmail.com",
    phone: "+971557007836",
    location: "Burjuman, Dubai, UAE",
    experience: 3,
    education: "MBA in Finance & HR (2022), B.Com (2019)",
    languages: ["English", "Hindi", "Malayalam"],
    summary: "HR professional with 3+ years of experience in HR Operations, Recruitment, and Employee Relations in the UAE. Experienced in MOHRE and labor accommodation management.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: true,
      bulkHiring: true,
      ats: false,
      linkedinRecruiter: false,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Managed full lifecycle recruitment cycle from job posting to final onboarding.",
      talentAcquisition: "Proven expertise in talent acquisition and onboarding.",
      whiteCollar: "Successfully recruited white-collar employees for transport and retail sectors.",
      blueCollar: "Recruited blue-collar workers and managed labor accommodation for 100+ employees.",
      bulkHiring: "Hired 100+ employees including blue-collar and administrative staff.",
      uaeExperience: "Worked in Dubai, UAE. Experienced in UAE Labour Law, MOHRE, GDRFA, and ICP processing."
    }
  },
  {
    id: "c11",
    name: "Raed El Kholy",
    title: "Recruitment Consultant / TA Specialist",
    email: "raed.elkholy555@gmail.com",
    phone: "+971507286859",
    location: "Al Rigga, Dubai, UAE",
    experience: 5,
    education: "Professional Master in HR (2024), Bachelor's in Law (2022)",
    languages: ["Arabic (Mother Tongue)", "English (Fluent)"],
    summary: "HR and Talent Acquisition Specialist with 5 years of experience in recruitment, administrative support, and HR compliance in Egypt and the UAE (Real Estate, Exchange, Retail).",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: false,
      bulkHiring: false,
      ats: true,
      linkedinRecruiter: true,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Managed end-to-end recruitment processes from job posting to onboarding (Top House Real Estate).",
      talentAcquisition: "Specialized in talent acquisition, screening, and sourcing strategies.",
      whiteCollar: "Recruited for corporate, real estate, and financial office-based roles.",
      ats: "Familiar with HRIS systems and database/CRM management tools.",
      linkedinRecruiter: "Experienced in sourcing candidates through LinkedIn and job portals.",
      uaeExperience: "Based in Dubai, UAE. Worked as recruitment consultant for Dubai-based companies."
    }
  },
  {
    id: "c12",
    name: "Hashmat Ara",
    title: "HR Officer / Manager",
    email: "hashmatara1@gmail.com",
    phone: "+971561769399",
    location: "Sharjah, UAE",
    experience: 12,
    education: "MS in HR (NUML), MBA in HRM",
    languages: ["English", "Urdu", "Pushto"],
    summary: "HR Professional with years of experience in healthcare HR management and hospital administration. Skilled in compliance, payroll coordination, and recruitment.",
    criteriaMatches: {
      endToEnd: true,
      talentAcquisition: true,
      whiteCollar: true,
      blueCollar: false,
      bulkHiring: false,
      ats: false,
      linkedinRecruiter: false,
      construction: false,
      interiorFitOut: false,
      joinery: false,
      mep: false,
      uaeExperience: true
    },
    justifications: {
      endToEnd: "Managed full HR operations and recruitment end-to-end at Peshawar Medical Center.",
      talentAcquisition: "Talent Acquisition listed as a core competency and experience area.",
      whiteCollar: "Recruited healthcare staff, medical officers, and administrative roles.",
      uaeExperience: "HR Officer in Sharjah, UAE. Strong knowledge of UAE labor laws and MOHRE compliance."
    }
  }
];
