const defaultCriteria = [
  { key: "genderFemale", label: "Female Candidate Only", category: "Strict Universal Filters", keywords: ["she", "her", "hers", "female", "woman", "ms", "mrs", "miss", "lady"] },
  { key: "excludedBackground", label: "No Excluded Backgrounds", category: "Strict Universal Filters", keywords: ["hr", "recruitment", "customer service", "call center", "accountant", "software engineer"] },
  { key: "targetTitle", label: "Target Sales/BD Title", category: "Target Profiles", keywords: ["business development", "bdm", "sales manager", "sales executive", "account manager"] },
  { key: "exhibitionsExp", label: "Exhibitions/Events Experience", category: "Industry Specializations", keywords: ["exhibition", "exhibitions", "stands", "booth", "events", "expo", "trade shows", "fit-out"] },
  { key: "uaeExperience", label: "UAE/Gulf Experience", category: "Geography", keywords: ["uae", "dubai", "abu dhabi", "sharjah", "gulf", "dwtc", "adnec"] },
  { key: "b2bSales", label: "B2B Sales & Lead Gen", category: "Core Skills", keywords: ["b2b sales", "client acquisition", "lead generation", "cold calling", "prospecting"] },
  { key: "closingNegotiation", label: "Closing & Negotiation", category: "Core Skills", keywords: ["negotiation", "closing deals", "proposal", "rfq", "tender"] },
  { key: "crmSystems", label: "CRM & Sales Tools", category: "Core Skills", keywords: ["crm", "hubspot", "salesforce", "zoho", "pipedrive", "odoo"] },
  { key: "strategicPlanning", label: "Strategic Planning & Team Management", category: "Manager Skills", keywords: ["strategic planning", "team management", "forecasting", "sales target", "revenue growth"] }
];

const candidatesData = [
  {
    id: "mock_c1",
    name: "Sarah Al-Mansoori",
    title: "Senior Business Development Manager - Exhibitions & Events",
    email: "sarah.mansoori@gmail.com",
    phone: "+971-52-1234567",
    location: "Dubai Marina, Dubai, UAE",
    gender: "female",
    genderReason: "Identified as Female (Name Sarah, pronouns she/her)",
    excludedBackground: false,
    backgroundReason: "Profile is strictly in B2B Exhibition Sales and Fit-Out.",
    experience: 8,
    exhibitionsExperience: 5,
    tier: "Manager",
    education: "Bachelor of Business Administration, Zayed University (2018)",
    languages: ["English", "Arabic (Native)"],
    summary: "Senior BDM with 8 years of overall experience, specializing in Exhibition Stand Design, Booth Fabrication, and Turnkey Pavilions at Dubai World Trade Centre (DWTC). Proven record of achieving 120% sales targets annually.",
    criteriaMatches: {
      genderFemale: true,
      excludedBackground: true,
      targetTitle: true,
      exhibitionsExp: true,
      uaeExperience: true,
      b2bSales: true,
      closingNegotiation: true,
      crmSystems: true,
      strategicPlanning: true
    },
    justifications: {
      genderFemale: "Verified Female candidate. Uses 'she/her' in profile summary.",
      excludedBackground: "No background in HR, customer service, or other excluded fields.",
      targetTitle: "Matches 'Senior Business Development Manager'.",
      exhibitionsExp: "5 years of experience in DWTC Stand Fabrication and Exhibition Booth Design.",
      uaeExperience: "Currently located in Dubai, working with Dubai World Trade Centre clients.",
      b2bSales: "Expertise in B2B corporate sales and client acquisition for major MNCs.",
      closingNegotiation: "Negotiated and closed stand fabrication deals worth AED 2.5 Million.",
      crmSystems: "Expert user of Salesforce CRM and Odoo Sales module.",
      strategicPlanning: "Led a team of 4 sales executives and designed the annual revenue forecasting strategy."
    }
  },
  {
    id: "mock_c2",
    name: "Yasmin Ibrahim",
    title: "Business Development Executive",
    email: "yasmin.ibrahim@outlook.com",
    phone: "+971-55-9876543",
    location: "Khalidiya, Abu Dhabi, UAE",
    gender: "female",
    genderReason: "Identified as Female (Name Yasmin)",
    excludedBackground: false,
    backgroundReason: "Profile is in Event Production and Trade Show Sales.",
    experience: 4,
    exhibitionsExperience: 2,
    tier: "Senior",
    education: "B.Sc. in Marketing, Cairo University (2021)",
    languages: ["English", "Arabic"],
    summary: "Result-oriented Business Development Executive with 4 years of experience (2 years in UAE) in trade show stand sales and event production. Specializes in cold calling, lead generation, and client relationship management.",
    criteriaMatches: {
      genderFemale: true,
      excludedBackground: true,
      targetTitle: true,
      exhibitionsExp: true,
      uaeExperience: true,
      b2bSales: true,
      closingNegotiation: true,
      crmSystems: true,
      strategicPlanning: false
    },
    justifications: {
      genderFemale: "Verified Female candidate.",
      excludedBackground: "No background in excluded fields.",
      targetTitle: "Matches 'Business Development Executive'.",
      exhibitionsExp: "Managed trade show stands and event production sales at ADNEC.",
      uaeExperience: "Based in Abu Dhabi, UAE with local market experience.",
      b2bSales: "Active in B2B cold calling, lead generation, and client acquisition.",
      closingNegotiation: "Experienced in submitting proposals and negotiating corporate sponsorships.",
      crmSystems: "Proficient in HubSpot and Zoho CRM.",
      strategicPlanning: "No direct team management or forecasting experience mentioned."
    }
  },
  {
    id: "mock_c3",
    name: "Mariam Hassan",
    title: "Sales Representative",
    email: "mariam.hassan@yahoo.com",
    phone: "+971-50-2345678",
    location: "Sharjah, UAE",
    gender: "female",
    genderReason: "Identified as Female (Name Mariam)",
    excludedBackground: false,
    backgroundReason: "Profile in Printing and Branding Sales.",
    experience: 2,
    exhibitionsExperience: 0,
    tier: "Junior",
    education: "Diploma in Graphic Arts and Marketing (2023)",
    languages: ["English", "Arabic"],
    summary: "Energetic Sales Representative with 2 years of experience in corporate printing, signage, and branding. Strong skills in client meetings, cold calling, and proposal submissions.",
    criteriaMatches: {
      genderFemale: true,
      excludedBackground: true,
      targetTitle: true,
      exhibitionsExp: false,
      uaeExperience: true,
      b2bSales: true,
      closingNegotiation: true,
      crmSystems: true,
      strategicPlanning: false
    },
    justifications: {
      genderFemale: "Verified Female candidate.",
      excludedBackground: "No background in excluded fields.",
      targetTitle: "Matches 'Sales Representative'.",
      exhibitionsExp: "No exhibitions experience, but background is in corporate printing and signage.",
      uaeExperience: "Located in Sharjah, UAE.",
      b2bSales: "Active in B2B lead generation, client meetings, and cold calling.",
      closingNegotiation: "Assisted in drafting proposals and closing printing deals.",
      crmSystems: "Used Odoo CRM for tracking customer interactions.",
      strategicPlanning: "No forecasting or management experience."
    }
  },
  {
    id: "mock_c4",
    name: "Ahmed Khalil",
    title: "Business Development Manager",
    email: "ahmed.khalil@gmail.com",
    phone: "+971-56-3456789",
    location: "Dubai, UAE",
    gender: "male",
    genderReason: "Filtered Out: MALE candidate. Gender requirement is FEMALE only.",
    excludedBackground: false,
    backgroundReason: "Experience is in Exhibition Stands Sales.",
    experience: 6,
    exhibitionsExperience: 4,
    tier: "Filtered Out",
    education: "B.Sc. in Commerce (2019)",
    languages: ["English", "Arabic"],
    summary: "Exhibition Stand Sales Manager with 6 years of experience in booth design and pavilion fabrication. Highly successful in B2B sales in the Gulf region.",
    criteriaMatches: {
      genderFemale: false,
      excludedBackground: true,
      targetTitle: true,
      exhibitionsExp: true,
      uaeExperience: true,
      b2bSales: true,
      closingNegotiation: true,
      crmSystems: true,
      strategicPlanning: true
    },
    justifications: {
      genderFemale: "Discarded: Candidate is Male. Universal filter requires Female candidates only.",
      excludedBackground: "No background in excluded fields.",
      targetTitle: "Matches target title.",
      exhibitionsExp: "Has 4 years exhibitions experience.",
      uaeExperience: "Based in Dubai, UAE.",
      b2bSales: "Strong B2B sales background.",
      closingNegotiation: "Closed multiple booth contracts.",
      crmSystems: "CRM proficient.",
      strategicPlanning: "Has forecasting experience."
    }
  },
  {
    id: "mock_c5",
    name: "Fatima Al-Jaber",
    title: "HR Specialist & Recruitment Officer",
    email: "fatima.jaber@recruit.sync",
    phone: "+971-58-4567890",
    location: "Al Ain, Abu Dhabi, UAE",
    gender: "female",
    genderReason: "Identified as Female (Name Fatima)",
    excludedBackground: true,
    backgroundReason: "Filtered Out: Excluded background detected (HR / Recruitment).",
    experience: 7,
    exhibitionsExperience: 0,
    tier: "Filtered Out",
    education: "MBA in Human Resources (2018)",
    languages: ["English", "Arabic"],
    summary: "HR Specialist with 7 years of experience in talent acquisition, employee relations, onboarding, and payroll administration. Proficient in ATS systems.",
    criteriaMatches: {
      genderFemale: true,
      excludedBackground: false,
      targetTitle: false,
      exhibitionsExp: false,
      uaeExperience: true,
      b2bSales: false,
      closingNegotiation: false,
      crmSystems: true,
      strategicPlanning: false
    },
    justifications: {
      genderFemale: "Verified Female candidate.",
      excludedBackground: "Discarded: Core background is in HR/Recruitment, which is an excluded industry.",
      targetTitle: "Does not match target sales/BD titles.",
      exhibitionsExp: "No exhibitions or event management experience.",
      uaeExperience: "Based in Abu Dhabi, UAE.",
      b2bSales: "No B2B sales experience (focused on recruitment).",
      closingNegotiation: "No sales negotiation/closing experience.",
      crmSystems: "ATS/HRIS system experience.",
      strategicPlanning: "No sales strategic planning."
    }
  },
  {
    id: "mock_c6",
    name: "Dina Mourad",
    title: "Property Consultant / Real Estate Sales",
    email: "dina.mourad@realestate.ae",
    phone: "+971-54-5678901",
    location: "Dubai Marina, Dubai, UAE",
    gender: "female",
    genderReason: "Identified as Female (Name Dina)",
    excludedBackground: false,
    backgroundReason: "Profile is in Real Estate Sales, which is not an excluded background.",
    experience: 4,
    exhibitionsExperience: 0,
    tier: "General Sales",
    education: "Bachelor of Arts in English (2021)",
    languages: ["English", "Arabic"],
    summary: "Motivated Property Consultant with 4 years of experience in high-end real estate sales. Specialized in lead generation, client presentations, and closing deals.",
    criteriaMatches: {
      genderFemale: true,
      excludedBackground: true,
      targetTitle: true,
      exhibitionsExp: false,
      uaeExperience: true,
      b2bSales: true,
      closingNegotiation: true,
      crmSystems: true,
      strategicPlanning: false
    },
    justifications: {
      genderFemale: "Verified Female candidate.",
      excludedBackground: "No background in excluded fields (Real Estate is allowed).",
      targetTitle: "Matches Sales Executive/Consultant titles.",
      exhibitionsExp: "No exhibitions/events industry experience (Real estate focus).",
      uaeExperience: "Based in Dubai, UAE.",
      b2bSales: "Strong skills in prospecting and lead generation.",
      closingNegotiation: "Closed property sales worth millions of dirhams.",
      crmSystems: "Used Property Finder CRM and Salesforce.",
      strategicPlanning: "No team management or corporate forecasting."
    }
  }
];
